# tasks/install-git.yml
# Debian/Ubuntu
- name: Install git (Debian/Ubuntu)
  become: yes
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: yes
  when: is_debian

# RHEL/CentOS/Fedora/Amazon
- name: Install git (RHEL/CentOS/Fedora/Amazon)
  become: yes
  ansible.builtin.dnf:
    name: git
    state: present
    disablerepo: "pgdg*"
  when: is_rpm

