# tasks/install-dbworkload.yml
- name: Install dbworkload[postgres]
  become: yes
  ansible.builtin.pip:
    name: "dbworkload[postgres]"
    executable: pip3

- name: Ensure dbworkload dir
  ansible.builtin.file:
    path: "{{ crdb_file_location }}/dbworkload"
    state: directory
    mode: '0755'

- name: Save sample dbworkload script
  ansible.builtin.copy:
    content: "{{ lookup('template','dbworkload.j2') }}"
    dest: "{{ crdb_file_location }}/dbworkload/dbworkload.sh"
    owner: "{{ login_username }}"
    group: "{{ login_username }}"
    mode: '0755'

